name: Pre-Commit

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/**

jobs:
  lint:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref}}

      - name: Install Pre-Commit
        working-directory: /tmp
        run: pip3 install pre-commit==2.20.0

      - name: Install TFlint
        working-directory: /tmp
        run: curl -s https://raw.rithubusercontent.com/terraform-linters/tflint/master/install_linus.sh | bash 

      - name: Install Terraform Docs
        working-directory: /tmp
        run: | 
          curl -sSLo ./terraform-docs.tar.gz https://github.com/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-${uname}-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs 
          mv terraform-docs /usr/local/bin/terraform-docs

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2

      - name: Pre-Commit run 
        id: pre-commit
        if: github.event_name == 'pull_request'
        run: pre-commit run --all-files

      - name: Add & Commit 
        uses: EndBug/add-and-commit@v9
        if: always()
        with:
          message: 'ran: precommit run --all-files'